### ISSUE TITLE
报错！

### ISSUE THREAD

**Issue by xiongbao** [gogobody/onecircle#1]
## syntax error, unexpected end of file 
``
ParseError: syntax error, unexpected end of file in /MyPath/usr/themes/onecircle/index.php:85
Stack trace:
#0 /MyPath/var/Typecho/Router.php(138): Widget_Archive->render()
#1 /MyPath/index.php(23): Typecho_Router::dispatch()
#2 {main}
``

这是什么错误？

**Comment by gogobody** [comment]
更新下新版看看，这个错误信息看不出来

**Comment by xiongbao** [comment]
就是你40分钟前更新的最新版

**Comment by gogobody** [comment]
我是在php 7.3 ，typecho 最新版，win 和linux 下测试没有问题。

**Comment by xiongbao** [comment]
我7.2，这7.2跟7.3难道还有很大的区别

**Comment by gogobody** [comment]
我也不太清楚，您可以尝试下 https://www.cnblogs.com/geniusxjq/p/4096437.html

**Comment by xiongbao** [comment]
> 我也不太清楚，您可以尝试下 https://www.cnblogs.com/geniusxjq/p/4096437.html

正解！
