### ISSUE TITLE
分类图片问题

### ISSUE THREAD

**Issue by Cuiyim** [gogobody/onecircle#18]
分类图片全变成了默认的图片,即使在分类描述中设置了也只是头像变了
![image](https://user-images.githubusercontent.com/51844650/133970054-4f02d424-2979-4ff4-b0c9-12f210049612.png)

**Comment by gogobody** [comment]
fixed!

**Comment by Cuiyim** [comment]
噗,,,演示站是跟随特定分类的头像的呀
![image](https://user-images.githubusercontent.com/51844650/133972161-b85ff315-c091-43f6-8561-49275489fbb4.png)

**Comment by gogobody** [comment]
刚刚已经修复了

**Comment by Cuiyim** [comment]
这就去更新新版本  哈哈
