### ISSUE TITLE
视频样式错误

### ISSUE THREAD

**Issue by Cuiyim** [gogobody/onecircle#19]
错误的样式
![image](https://user-images.githubusercontent.com/51844650/134049729-9221b24b-f4f7-46d2-b7ca-1e80e63ed468.png)
![image](https://user-images.githubusercontent.com/51844650/134050119-7ad8af87-a9db-45f5-940b-061f827ef78b.png)

正确的样式
![image](https://user-images.githubusercontent.com/51844650/134049993-8f5ea6c5-51c6-42db-87f4-89db729db660.png)

**Comment by gogobody** [comment]
前台发布就是下面的样式，上面的是joe编辑器的，和前台解析不一样
