### ISSUE TITLE
无法关注，无法私信

### ISSUE THREAD

**Issue by nanyancc** [gogobody/onecircle#20]
点击我的私信和系统消息都显示404
![](https://cdn.jsdelivr.net/gh/HenryHe613/Pic/20211004234054.png)
![](https://cdn.jsdelivr.net/gh/HenryHe613/Pic/20211004234139.png)

**Comment by nanyancc** [comment]
点了关注之后没有任何反应，

**Comment by nanyancc** [comment]
[网址](http://www.redmove.ga/)来一条

**Comment by nanyancc** [comment]
左下角的赞赏也打不开？？

**Comment by nanyancc** [comment]
您上线啦？

**Comment by gogobody** [comment]
安装插件OneCircle，并正确开启伪静态，搜typecho 伪静态

**Comment by nanyancc** [comment]
> 安装插件OneCircle，并正确开启伪静态，搜typecho 伪静态

好的，我试试

**Comment by nanyancc** [comment]
OneCircle安装了，伪静态也开了，还是不行

**Comment by nanyancc** [comment]
给您开管理员了

**Comment by gogobody** [comment]
可以尝试关闭其他插件，重新启用onecircle插件，其他问题国庆回来之后解决。

**Comment by gogobody** [comment]
看了下，你的插件不是最新，请更新后，重新启用插件

**Comment by nanyancc** [comment]
更新了，没有任何变化

**Comment by nanyancc** [comment]
> 可以尝试关闭其他插件，重新启用onecircle插件，其他问题国庆回来之后解决。

OK

**Comment by gogobody** [comment]
请开启typecho debug。在config.inc.php里加入

define('__TYPECHO_DEBUG__', true);

**Comment by nanyancc** [comment]
开启了

**Comment by gogobody** [comment]
没开启，检查下

**Comment by nanyancc** [comment]
![image](https://user-images.githubusercontent.com/59521292/136655627-b3ee9076-87f8-4cc6-b075-d8d3c5dc6d7d.png)

**Comment by nanyancc** [comment]
主机重启了，应该可以了

**Comment by gogobody** [comment]
![image](https://user-images.githubusercontent.com/16953662/136655730-61aa2307-7f79-496c-b208-7b2c25d9c3ee.png)
没有显示debug 信息，还是无效的

**Comment by nanyancc** [comment]
啊这

**Comment by nanyancc** [comment]
我这代码改了个寂寞

**Comment by nanyancc** [comment]
define('__TYPECHO_DEBUG__', true);
应该是这个

**Comment by nanyancc** [comment]
现在应该可以了
您是在哪里看debug的？

**Comment by gogobody** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Typecho_Db_Query_Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in /home/ftp/s/s3146748/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /home/ftp/s/s3146748/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('INSERT INTO typ...', Object(PDO), 2, 'INSERT')
#1 /home/ftp/s/s3146748/usr/themes/onecircle/libs/UserFollow.php(62): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /home/ftp/s/s3146748/usr/themes/onecircle/libs/route.php(61): UserFollow::addFollow('68', '1')
#3 /home/ftp/s/s3146748/usr/themes/onecircle/libs/route.php(6): rootRouteFunc(Object(Widget_Archive))
#4 /home/ftp/s/s3146748/usr/themes/onecircle/functions.php(102): parseRout(Object(Widget_Archive))
#5 /home/ftp/s/s3146748/var/Widget/Archive.php(1378): themeInit(Object(Widget_Archive))
#6 /home/ftp/s/s3146748/var/Typecho/Widget.php(221): Widget_Archive->execute()
#7 /home/ftp/s/s3146748/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Archive', NULL, NULL)
#8 /home/ftp/s/s3146748/index.php(23): Typecho_Router::dispatch()
#9 {main}

检查一下你的 user_follow表 id 是不是没有自增

**Comment by nanyancc** [comment]
![image](https://user-images.githubusercontent.com/59521292/136656580-15c8d12b-83fc-4504-b43b-e2b65ae0bd9c.png)
全都是我关注的几个

**Comment by gogobody** [comment]
检查结构里， id 是不是没有自增

**Comment by HenryHe613** [comment]
是我孤陋寡闻了，结构是什么em

**Comment by nanyancc** [comment]
![image](https://user-images.githubusercontent.com/59521292/136656729-12580dca-56d9-4796-9d1e-70a8f4f0c0ae.png)

**Comment by gogobody** [comment]
点修改，id，自增勾上
![image](https://user-images.githubusercontent.com/16953662/136656796-467b47e8-ed46-4888-bffa-a377c7feb5f5.png)

**Comment by nanyancc** [comment]
![image](https://user-images.githubusercontent.com/59521292/136657021-ca5f1e1e-f8f1-46ca-bd93-8ea5c3f5c3f3.png)

**Comment by gogobody** [comment]
先把id 为0 那条数据删了在修改

**Comment by nanyancc** [comment]
ok成功了！

**Comment by nanyancc** [comment]
![image](https://user-images.githubusercontent.com/59521292/136657274-aa3ef38f-ffb0-4f6d-bcf2-93ca01bd9879.png)
那么这个私聊怎么用？

**Comment by gogobody** [comment]
搜索关注者

**Comment by nanyancc** [comment]
ok那么系统消息在哪里？
