### ISSUE TITLE
颜文字样式

### ISSUE THREAD

**Issue by LovesAsuna** [gogobody/onecircle#8]
syntax error, unexpected end of file
ParseError: syntax error, unexpected end of file in /usr/share/nginx/typecho/usr/themes/onecircle/includes/post-pagination.php:47
Stack trace:
#0 /usr/share/nginx/typecho/usr/themes/onecircle/index.php(90): Widget_Archive->need('includes/post-p...')
#1 /usr/share/nginx/typecho/var/Widget/Archive.php(2022): require_once('/usr/share/ngin...')
#2 /usr/share/nginx/typecho/var/Typecho/Router.php(138): Widget_Archive->render()
#3 /usr/share/nginx/typecho/index.php(23): Typecho_Router::dispatch()
#4 {main}
![79ZSO5K H~0`YOJD%LZO(L4](https://user-images.githubusercontent.com/32810896/111620287-79946a00-8821-11eb-828b-8d86c58aea2f.png)

**Comment by gogobody** [comment]
插件，php7

**Comment by LovesAsuna** [comment]
完全符合

**Comment by gogobody** [comment]
代码没问题，我的测试版本 7.2 。另外可以看看是否有短标签问题：https://blog.csdn.net/u014175572/article/details/52798684/

**Comment by LovesAsuna** [comment]
确实是短标签的问题，php涉及知识盲区了感谢

**Comment by LovesAsuna** [comment]
另外我还有留意到似乎有些图片是直接从moe.best抓过来的但似乎它做了一些访问限制所以导致有一些图片会无法抓取到
![H9QIQ_@_A_4$JG3W}`QW$@B](https://user-images.githubusercontent.com/32810896/111721258-76899000-889a-11eb-9d7a-1b571e076dca.png)
![U8`{0QK RW63R1$XD} K)DI](https://user-images.githubusercontent.com/32810896/111721262-77babd00-889a-11eb-818e-40e6986d920b.png)

**Comment by gogobody** [comment]
防盗链，与主题无关。

**Comment by LovesAsuna** [comment]
颜文字的地方稍微有点错位另外点开之后的透明背景很影响观看
![W( S 0MB@WF6P~V_OB$}8L](https://user-images.githubusercontent.com/32810896/111763426-1831d100-88dd-11eb-9b7c-d4ccdc647ea8.png)
![K(63_R8@C_3OVBT1`2TK$F7](https://user-images.githubusercontent.com/32810896/111763432-18ca6780-88dd-11eb-817d-2280bfad4d94.png)

**Comment by gogobody** [comment]
有空在改吧，主题的目的是不使用后台

**Comment by gogobody** [comment]
solved~
