### ISSUE TITLE
圈子分类图标

### ISSUE THREAD

**Issue by LovesAsuna** [gogobody/onecircle#9]
关于分类图标，似乎除了设置一个默认的分类图标，就不能对每一个分类进行详细的图标设置，所有的分类都采用了那一个默认的图标

**Comment by gogobody** [comment]
https://www.yuque.com/docs/share/05f40cac-980f-4e53-8b92-ed9728b8dc50?#%E3%80%8AOneCircle%20%E4%B8%BB%E9%A2%98%E8%AF%B4%E6%98%8E%E3%80%8B

**Comment by LovesAsuna** [comment]
我觉得单独做一个图片选项会人性化一点

**Comment by gogobody** [comment]
那边没接口，只能手动这样输入，正则匹配
